fun main(args: Array<String>) {
    val service = WallNotes()
    service.add("1st note", "hello world")
    service.add("day 2", "all is good")
    service.createComment(2, "what about you?")
    service.createComment(2, "my day is good too")
    service.createComment(2, "i saw nice sunrise")
    service.getById(2)?.deleteComment(1)
    println()
    println("service")
    service.get()
    service.getById(12)?.deleteComment(1)

    println()
    println("service2")
    val service2 = WallNotes()
    service2.add("1st note", "hello world")
    service2.add("day 2", "all is good")
    service2.createComment(2, "what about you?")
    service2.createComment(2, "my day is good too")
    service2.createComment(2, "i saw nice sunrise")
    service2.createComment(2, "my day is good too")
    service2.createComment(2, "i saw nice sunrise 2")
    service.createComment(2, "another comment")
    //service2.getById(2)?.restoreComment(1)
    service2.getById(2)?.getComments()
    println()
    println("service")
    service.getById(2)?.getComments()

    val service3= WallNotes()
    service3.add("1st note", "hello world")
    service3.add("day 2", "all is good")
    service3.createComment(2, "what about you?")
    service3.createComment(2, "my day is good too")
    service3.createComment(2, "i saw nice sunrise")
    service3.getById(2)?.deleteComment(1)
    println("service3")
    println(service3.getById(112)?.restoreComment(3))
}